### ISSUE TITLE
FHR: App is getting crashed in a scenario.

### ISSUE THREAD

**Issue by akanshajindal23** [MyDieticianDev/Client_Android#21]
STEPS TO REPRODUCED:
1) Launch the app.
2) Login to the app.
3) Add the data on Profile Setup page.
4) Click on next button.
5) Click on Previous button.
6) Again click on next button.

Observation:
App is getting crashed.

NOTE: Not able to attached the video.

**Comment by MyDieticianDev** [comment]
fixed
