### ISSUE TITLE
Profile -> Edit option is adding new profile, not able to edit the existing profile.

### ISSUE THREAD

**Issue by akanshajindal23** [MyDieticianDev/Client_Android#26]
STEPS TO REPRODUCED:

1) Launch the app.
2) Login to the app.
3) Add the profile.
4) Click on Next -> Next -> Save.
5) Click on Edit button.
6) Enter data.

Observation:
New data will be added.

**Comment by ssunderk** [comment]
This is fixed.  'Basic Info' can be edited . I could not see edit button. it is Basic Info and Care team button
