### ISSUE TITLE
Forget Password is not working properly.

### ISSUE THREAD

**Issue by akanshajindal23** [MyDieticianDev/Client_Android#27]
STEPS TO REPRODUCED:

1) Launch the app.
2) Login to the app.
3) Uninstall the app.
4) Install the app again.
5) Enter same username and click on forget password?
6) Enter username and enter new password and click on submit button.

OBSERVATION:
Email not registered error is coming.

**Comment by vyarrams** [comment]
Fixed this issue. Please check in the apk that will be shared from now on.
