### ISSUE TITLE
Care Team: Control is skipping to the next field from "Role" and "State" when using soft key for next.

### ISSUE THREAD

**Issue by akanshajindal23** [MyDieticianDev/Client_Android#28]

**Comment by akanshajindal23** [comment]
STEPS TO REPRODUCED:

1) Launch the app.
2) Add the Profile and click on Next -> Next
3) Go the the care team page enter the value one by one for all the field and use soft key for entering the data in next field.

Observation:
From "Business" it is directly jump to the Address1 and from "City" it is jumping to phone.

**Comment by MyDieticianDev** [comment]
fixed
