### ISSUE TITLE
Care Team: After saving the data, Phone data is showing for Email and Email data is showing for phone 

### ISSUE THREAD

**Issue by akanshajindal23** [MyDieticianDev/Client_Android#29]
STEPS TO REPRODUCED:

1) Launch the app.
2) Add the Profile and click on Next -> Next
3) Go the the care team page enter all the values one by one for all the fields.
4) Click on Add button.

Observation:
Data is showing vice versa for Phone and Email fields.
![screenshot_20180719-003046](https://user-images.githubusercontent.com/39299427/42902573-bf560c5e-8aec-11e8-9c07-07dcffc12651.png)

**Comment by ssunderk** [comment]
fixed
