### ISSUE TITLE
Profile Setup-> Not able to add the data, even after entering all the data. 

### ISSUE THREAD

**Issue by akanshajindal23** [MyDieticianDev/Client_Android#30]
1) Launch the app.
2) Login to the app.
3) Enter the data for all the fields mentioned in the attached screenshot.

Observation:
Not able to add the data, even after entering all the data.
Error Msg: "
![profile](https://user-images.githubusercontent.com/39299427/42956015-71578e0a-8b9c-11e8-81ea-614ad0555d73.png)
Please enter all the mandatory fields."

**Comment by MyDieticianDev** [comment]
this was a date issue. the date was not validated correctly. Issue has now been fixed
