### ISSUE TITLE
Pop up to select email id is coming as soon as landing on the Login page

### ISSUE THREAD

**Issue by akanshajindal23** [MyDieticianDev/Client_Android#31]
STEPS TO REPRODUCED:

1) Launch the app.
2) User will navigate to the login page.

Observation:
Pop up to select email id is showing.
![loginpage](https://user-images.githubusercontent.com/39299427/42957276-c22b6e16-8b9f-11e8-8910-56866884f7de.png)

**Comment by MyDieticianDev** [comment]
issue is fixed and will be available in next build
