### ISSUE TITLE
Proper error msg is not shown after entering invalid username and password.

### ISSUE THREAD

**Issue by akanshajindal23** [MyDieticianDev/Client_Android#32]
STEPS TO REPRODUCED:

1) Launch the app.
2) Enter the email address which is not registered.
3) Enter password.

Observation: 
Error msg is shown - "Unable to login currently. Please try after sometime"
![error_msg](https://user-images.githubusercontent.com/39299427/42957905-92a5083a-8ba1-11e8-9d61-1e345c9cbc31.png)

**Comment by vyarrams** [comment]
This is fixed. will be available in the next apk from now on.
