### ISSUE TITLE
Forget Password: PIN is successfully sent on unregistered email address.

### ISSUE THREAD

**Issue by akanshajindal23** [MyDieticianDev/Client_Android#34]
STEPS TO REPRODUCED:

1) Launch the app.
2) Click on forget password?
3) Enter a valid email id.
4) Enter the password

Observation:
PIN is sent successfully.

5) Enter the PIN on OTP verification page.

Observation:
Getting a error msg - "Unable to reset password currently.  Please try after sometime."

**Comment by vyarrams** [comment]
This is fixed. we now verify if the email is registered or not before sending verification code.
