### ISSUE TITLE
Heath Data->Clicking on Lab Data is not showing any thing

### ISSUE THREAD

**Issue by akanshajindal23** [MyDieticianDev/Client_Android#37]
![labdata](https://user-images.githubusercontent.com/39299427/43033244-588449d8-8ce4-11e8-9cbc-e820de40f4fd.png)
1) Launch the app.
2) Login to the app.
3) Enter the profile data.
4) Click on Next
5) Click on + icon.
6) Click on Lab Data.

Observation:
Nothing is showing after clicking on Lab Data.

**Comment by MyDieticianDev** [comment]
fixed in the latest build.
