### ISSUE TITLE
App is getting crashed after clicking on medications from Profile dashboard

### ISSUE THREAD

**Issue by akanshajindal23** [MyDieticianDev/Client_Android#38]
1) From the profile dashboard page click on + icon.
2) Click on + icon
3) Click on Medications ->User will navigate to the dashboard page
4) Repeat step 2 and 3

Observation:
App is getting crashed.
![screenshot_20180721-125701](https://user-images.githubusercontent.com/39299427/43033342-79d27c66-8ce6-11e8-88a1-25f6beddef1f.png)

**Comment by MyDieticianDev** [comment]
fixed in the latest build.
