### ISSUE TITLE
Remove the red box surrounding the delete button.

### ISSUE THREAD

**Issue by sujaykondanekar** [MyDieticianDev/Client_Android#51]
Remove the red box surrounding the delete button. It should instead be a red delete icon only(currently white)
![image](https://user-images.githubusercontent.com/28152555/43148910-e4f42306-8f83-11e8-8786-adcbd278386a.png)

**Comment by MyDieticianDev** [comment]
This is the same image provided by harsha. I have changed it now. used gray color delete icon as per standard
